### ISSUE TITLE
How to let users login if the "login route" is protected by the master access_token

### ISSUE THREAD

**Issue by Mikou** [diegohaz/generator-rest-example#3]
This is a question more than an issue.

https://github.com/diegohaz/generator-rest-example/blob/c05c776332efab0336ca7e5c518143e585420225/src/api/auth/auth.router.js#L22

I am wondering how to let my users login if the "login route" is protected by the master access_token? (my users are not supposed to know the master key.)

My scenario: I have a "form" in a front-end (react) app that prompts the user for his email and password. how can I get the "master access_token" along?

I am considering removing completely the requirement of the "master access_token" in my project for the login route. Is this a bad idea?
 
Some guidance would be appreciated.

**Comment by diegohaz** [comment]
Hey, @Mikou. Take a look at this issue: https://github.com/diegohaz/rest/issues/67
